# Pull Geth into a second stage deploy alpine container
FROM alpine:latest

RUN apk add --no-cache ca-certificates
COPY /story /usr/local/bin/

EXPOSE 8545 8546 30303 30303/udp

WORKDIR /root/.story/story